# Generated by Django 5.1.2 on 2025-01-29 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='itemmodel',
            name='itemCat',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='user',
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_date', models.CharField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField()),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.creditcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='CreditCardModel',
        ),
        migrations.DeleteModel(
            name='ItemModel',
        ),
        migrations.DeleteModel(
            name='TransactionItem',
        ),
        migrations.DeleteModel(
            name='TransactionModel',
        ),
        migrations.DeleteModel(
            name='UserCard',
        ),
    ]
